### ISSUE TITLE
Unresolved methods in code

### ISSUE THREAD

**Issue by TheNewBob** [EsotericSoftware/spine-superspineboy#4]
Trying to get this to run in an Intellij project without much success while trying to evaluate Spine. I resolved all the dependencies, but there are 3 unresolvable methods.

This might be due to the example using an older version of spine-libgdx, I'm not sure. I'm pulling the newest version from maven (3.5.51.1)

The methods in question are:
* AnimationState.TrackEntry.setTime()
* AnimationState.TrackEntry.endTime()
* Bone.getWorldRotation()

I cannot spot these in the API reference either, so my guess is they were deprecated and removed at some point? There seem to be comparable methods, but not quite equivalent, and fixing (and quite possibly breaking) the example source code before I can even run the thing is not exactly what I had in mind.
Considering there don't seem to be many integration examples for spine with libGDX around, this is somewhat disheartening.

**Comment by NathanSweet** [comment]
You don't need Maven to get this running -- all the JARS are in the libs folder. It may be the old fashioned way, but it is easy and works!

You're right this project has gotten a bit dated. I've updated Super Spineboy to the latest spine-runtimes (3.7.94) and libgdx (1.9.10).

**Comment by TheNewBob** [comment]
Yeah, that did it, thanks a lot for the prompt reaction!
